[package]
name = "reth-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reth RPC implementation"

[lints]
workspace = true

[dependencies]
# reth
reth-interfaces.workspace = true
reth-primitives.workspace = true
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-network-api.workspace = true
reth-network.workspace = true
reth-rpc-engine-api.workspace = true
reth-revm = { workspace = true, features = ["js-tracer"] }
reth-tasks.workspace = true
reth-consensus-common.workspace = true
reth-rpc-types-compat.workspace = true
revm-inspectors.workspace = true
reth-node-api.workspace = true

# eth
alloy-rlp.workspace = true
alloy-dyn-abi = { workspace = true, features = ["eip712"] }
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
revm = { workspace = true, features = [
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_no_base_fee",
] }
revm-primitives = { workspace = true, features = ["serde"] }

# rpc
jsonrpsee.workspace = true
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.24"
jsonwebtoken = "8"

## required for optimism sequencer delegation
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
], optional = true }

# async
async-trait.workspace = true
tokio = { workspace = true, features = ["sync"] }
tower = "0.4"
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = "0.7"
pin-project.workspace = true
rayon.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
bytes.workspace = true
secp256k1 = { workspace = true, features = [
    "global-context",
    "rand-std",
    "recovery",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-futures = "0.2"
schnellru.workspace = true
futures.workspace = true
derive_more = "0.99"
lazy_static = "*"

[dev-dependencies]
jsonrpsee = { workspace = true, features = ["client"] }
assert_matches.workspace = true
tempfile.workspace = true
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-node-ethereum.workspace = true
reth-node-optimism.workspace = true

[features]
optimism = [
    "dep:reqwest",
    "reth-primitives/optimism",
    "reth-rpc-types-compat/optimism",
    "reth-network-api/optimism",
    "reth-network/optimism",
    "reth-provider/optimism",
    "reth-transaction-pool/optimism",
    "reth-node-api/optimism",
]
