[package]
name = "reth-beacon-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-beacon-consensus-core.workspace = true
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-stages.workspace = true
reth-db.workspace = true
reth-provider.workspace = true
reth-rpc-types.workspace = true
reth-tasks.workspace = true
reth-payload-builder.workspace = true
reth-payload-validator.workspace = true
reth-prune.workspace = true
reth-snapshot.workspace = true
reth-tokio-util.workspace = true
reth-node-api.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures.workspace = true

# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true
schnellru.workspace = true
cfg-if = "1.0.0"

[dev-dependencies]
# reth
reth-payload-builder = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-stages = { workspace = true, features = ["test-utils"] }
reth-blockchain-tree = { workspace = true, features = ["test-utils"] }
reth-db = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-rpc-types-compat.workspace = true
reth-tracing.workspace = true
reth-revm.workspace = true
reth-downloaders.workspace = true
reth-node-ethereum.workspace = true
reth-node-optimism.workspace = true

assert_matches.workspace = true

[features]
optimism = [
  "reth-primitives/optimism",
  "reth-interfaces/optimism",
  "reth-provider/optimism",
  "reth-rpc-types/optimism",
  "reth-payload-builder/optimism",
  "reth-blockchain-tree/optimism",
  "reth-node-api/optimism",
]
